version: '3'

services:
  metatree-saturn:
    image: ${SATURN_IMAGE}
    container_name: metatree-saturn
    environment:
      USE_DOCKERCOMPOSE: 'true'
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL:?Please configure KEYCLOAK_SERVER_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:?Please configure KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:?Please configure KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:?Please configure KEYCLOAK_CLIENT_ID}
      METATREE_URL: ${METATREE_URL:?Please configure METATREE_URL}
      AUDIT_LOG_ROOT: ${AUDIT_LOG_ROOT:-/data/saturn/audit}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ./vocabulary.ttl:/opt/config/vocabulary.ttl
      - ./views.yaml:/opt/config/views.yaml
      - database:/data/saturn/db
      - files:/data/saturn/files
      - audit:/data/saturn/audit
      - ./ssl/extra_certs.pem:/opt/extra_certs.pem
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: metatree-saturn
    networks:
      - nginx-proxy-network
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${DOCKER_HOST_IP}

  metatree-pluto:
    image: ${PLUTO_IMAGE}
    container_name: metatree-pluto
    environment:
      USE_DOCKERCOMPOSE: 'true'
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:?Please configure KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:?Please configure KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL:?Please configure KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:?Please configure KEYCLOAK_REALM}
      METATREE_URL: ${METATREE_URL:?Please configure METATREE_URL}
      PLUTO_LOGLEVEL: ${PLUTO_LOGLEVEL:-"INFO"}
      PLUTO_CONNECT_TIMEOUT_MILLIS: ${PLUTO_CONNECT_TIMEOUT_MILLIS:-600000}
      PLUTO_SOCKET_TIMEOUT_MILLIS: ${PLUTO_SOCKET_TIMEOUT_MILLIS:-2000}
      NGINX_HOST: localhost
      NGINX_PORT: 9080
    ports:
      - 9080:9080
    restart: unless-stopped
    depends_on:
      - metatree-saturn
    volumes:
      - ./ssl/extra_certs.pem:/opt/extra_certs.pem
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: metatree-pluto
    networks:
      - nginx-proxy-network
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${DOCKER_HOST_IP}

volumes:
  database:
  files:
  audit:

networks:
  nginx-proxy-network:
    driver: bridge

