views:
  - name: Files
    title: Files
    itemName: Name
    types:
      - https://sils.uva.nl/ontology#ExternalFile
    columns:
      - name: externalFileLink
        title: File link
        source: https://sils.uva.nl/ontology#externalFileLink
        type: link
    joinColumns:
      - name: objectSpecies
        title: Object species
        source: https://sils.uva.nl/ontology#objectSpecies
        rdfType: https://sils.uva.nl/ontology#Species
        sourceClass: https://sils.uva.nl/ontology#Object
        sourceClassName: Object
        type: term      
    join:
      - view: Studies
        on: https://sils.uva.nl/ontology#study 
        reverse: true
        include:
          - studyTitle
          - studyGoal               
  
  - name: Studies
    title: Studies
    itemName: Study    
    types:
      - https://sils.uva.nl/ontology#Study      
    columns:
      - name: studyTitle
        title: Study Title
        source: https://sils.uva.nl/ontology#studyTitle                        
        type: text     
      - name: studyGoal
        title: Study Goal
        source: https://sils.uva.nl/ontology#studyGoal                
        type: text     
    joinColumns:
      - name: objectSpecies
        title: Object species
        source: https://sils.uva.nl/ontology#objectSpecies
        rdfType: https://sils.uva.nl/ontology#Species
        sourceClass: https://sils.uva.nl/ontology#Object
        sourceClassName: Object
        type: term    
    join:
      - view: Files
        on: https://sils.uva.nl/ontology#study         
        include:
          - externalFileLink

  - name: Departments
    title: Departments
    itemName: Department    
    types:      
      - https://sils.uva.nl/ontology#Department      
    columns:
      - name: department
        title: Department
        source: https://sils.uva.nl/ontology#departmentDescription
        type: text                       
    joinColumns:
      - name: objectSpecies
        title: Object species
        source: https://sils.uva.nl/ontology#objectSpecies
        rdfType: https://sils.uva.nl/ontology#Species
        sourceClass: https://sils.uva.nl/ontology#Object
        sourceClassName: Object
        type: term
  